$kind: http-request
method: GET
url: '{{baseUrl}}/api/v1/admin/settings'
order: 5000
headers:
  - key: Authorization
    value: Bearer {{adminToken}}
scripts:
  - type: afterResponse
    language: text/javascript
    code: |-
      pm.test('Admin settings get is 200', function () {
        pm.response.to.have.status(200);
      });
